version: '3.8'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shipping_system
      MYSQL_USER: kinzy
      MYSQL_PASSWORD: 1234
